---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-registry-sa
  namespace: tekton-pipelines
  annotations:
    description: "Service account for ADB Butler Tekton pipeline"
secrets:
  - name: docker-registry-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: tekton-pipelines
  annotations:
    description: "Docker registry credentials for ADB Butler pipeline"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipeline-role
  annotations:
    description: "Cluster role for ADB Butler Tekton pipeline"
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["tekton.dev"]
    resources: ["tasks", "taskruns", "pipelines", "pipelineruns"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipeline-rolebinding
  annotations:
    description: "Cluster role binding for ADB Butler Tekton pipeline"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-pipeline-role
subjects:
  - kind: ServiceAccount
    name: docker-registry-sa
    namespace: tekton-pipelines
